function [ signal_data_set ] = signal_null( raw_data_set )
%Returns a copy of the input raw data set.  Used for debugging
%   This function is used to debug the
%   Analysis.generate_signal_data_sets() and
%   Data_Set.create_signal_data_set() methods.

top=[ ...
    raw_data_set.left_date_times, ...
    raw_data_set.left_wait_times, ...
    raw_data_set.left_z_positions, ...
    ];

bottom=[ ...
    raw_data_set.right_date_times, ...
    raw_data_set.right_wait_times, ...
    raw_data_set.right_z_positions, ...
    ];
    
signal_data_set=Raw_Data_Set([top;bottom]);

end

